---
title: "Summary of hemochromatosis questionnaire answers"
author: "Elina Koskinen, Jonna Clancy and Mikko Arvas"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    theme: united
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(gtsummary)
library(likert)
library(readxl)
library(here)
#https://github.com/markolalovic/responsesR
#install.packages("devtools")
#library(devtools)
# install_github("markolalovic/responsesR")
library(responsesR)
```


# Data

## Import

```{r}
file <- here("data/Tulokset - hemokromatoosikysely vastaukset (ID 133620).xlsx")
data <- read_xlsx(file)

colnames(data)
```

```{r}
#remove open questions
data<- data %>% 
  select(
    -Kys8aFutureOpen,
    -Kys12aTrustOpen,
    -Kys13aMembertoBiobankOpen,
    -Kys15OtherWhere,
    -Kys21OtherResultsOpen,
    -Kys23SymptomsOpen,
    -Kys26cAttitudesinFamilyOpen
    
  )
summary(data)
```

 

## Process

```{r}

data <-  data %>% 
  rename(Kys20aBHFED = `Kys20aB-HFE-D`) %>% 
  mutate(
    Kys2Gender = factor(Kys2Gender),
    Kys3DonationCount = factor(Kys3DonationCount,ordered = TRUE),
    Kys9Useful = factor(
      Kys9Useful,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    Kys10Worry = factor(
      Kys10Worry,
      ordered = TRUE,
      #First you specify the levels in the original data , in the order that you want them to be
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      #Then you specify new names for them
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
      # > tmp$Kys10Worry
      #...
      # Levels: Totally agree < Partly agree < Neutral < Partly disagree < Totally disagree
      #> table(tmp$Kys10Worry)
      # 
      # Totally agree     Partly agree          Neutral  Partly disagree Totally disagree 
      # 3               12                0               10                5
    ),
    
    
    Kys11HealthPromotion = factor(
      Kys11HealthPromotion,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    
    Kys16Flexibility = factor(
      Kys16Flexibility,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    
    Kys17Support = factor(
      Kys17Support,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    
    Kys18Answers = factor(
      Kys18Answers,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    
    Kys24Influence = factor(
      Kys24Influence,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    
    Kys25Motivation = factor(
      Kys25Motivation,
      ordered = TRUE,
      levels = rev(c("Strongly agree","Partly agree","Neither agree nor disagree","Partly disagree","Strongly disagree")),
      labels =  rev(c("Totally agree","Partly agree","Neutral","Partly disagree","Totally disagree"))
    ),
    
    Kys5HowOften = factor(
      Kys5HowOften,
      ordered = FALSE,
      levels = c("More often than nowadays", "As per nowadays", "Less than nowadays", "Quitting donating blood because of the information received", "Quitting donating blood because of another reason, eg. Age or other barrier", "Can not tell")
    ),
    
    Kys6EasytoUnderstand = factor(
      Kys6EasytoUnderstand,
      ordered = TRUE,
      levels = c("No", "Can not tell", "Yes")
    ),
    
    Kys7Understanding = factor(
      Kys7Understanding,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys8Future = factor(
      Kys8Future,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys12Trust = factor(
      Kys12Trust,
      ordered = TRUE,
      levels = rev(c("Grown", "Partly grown", "Have not affected", "Partly decreased", "Decreased"))
    ),
    
    Kys13MembertoBiobank = factor(
      Kys13MembertoBiobank,
      ordered = TRUE,
      levels = rev(c("Grown", "Partly grown", "Have not affected", "Partly decreased", "Decreased"))
    ),
    
    Kys14Healthcare = factor(
      Kys14Healthcare,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys15aStudentHealth = factor(
      Kys15aStudentHealth,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys15bOccupational = factor(
      Kys15bOccupational,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys15cSpecialHealth = factor(
      Kys15cSpecialHealth,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys15dHealthCare = factor(
      Kys15dHealthCare,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys15ePrivate = factor(
      Kys15ePrivate,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    
    Kys19Attitude = factor(
      Kys19Attitude,
      ordered = TRUE,
      levels = rev(c("Positive", "Partly positive", "Neutral", "Partly negative", "Negative"))
    ),
    
    Kys22Diagnosis = factor(
      Kys22Diagnosis,
      ordered = FALSE,
      levels = c("Yes", "No", "Don't know")
    ),
    
    Kys23aTiredness = factor(
      Kys23aTiredness,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys23bJoint = factor(
      Kys23bJoint,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys23cType2DM = factor(
      Kys23cType2DM,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys26aFamily = factor(
      Kys26aFamily,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    
    Kys1Age	= as.numeric(Kys1Age),
    Kys4YearStarted = as.numeric(Kys4YearStarted),
    Kys20aBHFED = factor(
    Kys20aBHFED,
      ordered = FALSE,
      levels = c("Yes", "No")
    ),
    Kys20bFerrit = as.numeric(Kys20bFerrit),
    Kys20cTrfesat = as.numeric(Kys20cTrfesat),
    Kys20dHemoglobin = as.numeric(Kys20dHemoglobin),
    Kys20eMCV = as.numeric(Kys20eMCV),
    Kys20fALAT = as.numeric(Kys20fALAT),
    Kys26bNumberofRelatives = as.numeric(Kys26bNumberofRelatives)
  )

summary(data)
```



# Demographics

## Age by Gender

```{r}

p <- ggplot(data)
p <- p +  geom_histogram(aes(x=Kys1Age),binwidth = 5)
p <- p + facet_wrap(. ~ Kys2Gender)
p <- p + xlab("Age in years")
p

```


## Demographics Table 1

```{r}

table1 <-
  tbl_summary(
    data %>% rename(
      Age =  Kys1Age,
      YearStarted = Kys4YearStarted,
      DonationCount = Kys3DonationCount
    ),
    include = c(
      Age,
      YearStarted,  
      DonationCount
      ),
    by =  Kys2Gender
    
  ) %>%
  add_n()  # add column with total number of non-missing observations
table1
```

# Distributions of Likert scale questions


```{r} 
items = data %>% 
  select(Kys9Useful, Kys10Worry, Kys11HealthPromotion) %>% as.data.frame()
colnames(items) <- c(
  "Geenitiedon vastaanottaminen on hyödyllistä",
  "Geenitiedon vastaanottaminen ei herättänyt minussa huolta",
  "Biopankin geenitietoa pitäisi hyödyntää laajemmin terveyden edistämiseksi"
)

nlevels = 5
```


```{r}
q09 <- likert(
  items = as.data.frame(items),
  nlevels = nlevels
  
)
plot(q09, 
     type = "bar",
     wrap = 10,
     legend.position = "bottom",
     text.size=3,
     include.histogram = FALSE)
```

add all the questions here


# Distributions of lab values by gender

add here like age


```{r}

p <- ggplot(data)
p <- p + geom_histogram(aes(x=Kys20bFerrit, fill = Kys2Gender), binwidth = 0.2)
p <- p + facet_wrap(. ~ Kys2Gender)
p <- p + xlab("Ferritin results")
p <- p + scale_x_log10() + geom_vline(aes(xintercept = 15, col = "red")) + geom_vline(aes(xintercept = 500, col = "red"))
p


```   



